import numpy as np
def run():
    a=np.array([[1,0,0],[0,1,0],[0,0,1]])
    b=np.array([[0,2,0],[-3,-1,-2],[0,3,10]])
    c=np.zeros([3,1])
    d=np.array([[1],[2],[3]])
    e=np.array([[2],[3],[1]])
    print("c all zeros")
    print(c)
    print("a+b:")
    print(a+b)
    print("a-b:")
    print(a-b)
    #print("2*a:")
    #print(2*a)
    print("a*b:")
    print(a*b)
    print("a/b:")
    print(a/b)
    print("Transpose a:")
    print(np.transpose(a))
    print("Invert b:")
    print(np.inv(b))
    print(d)
    print(e)
    print("Cross d x e:")
    print(np.cross(d,e))
    print("Create range from [1-10[:")
    print(np.arange(1,10,0.5))
    print("random 3x2:")
    print(np.random(3,2))