/**********************************************************************
 * Extern for strftime
 * Generated by http://jmmk.github.io/javascript-externs-generator
 **********************************************************************/
var strftime = {
  "localize": function () {},
  "localizeByIdentifier": function () {},
  "timezone": function () {},
  "utc": function () {}
};
/**********************************************************************
 * End Generated Extern for strftime
/**********************************************************************/