/**********************************************************************
 * Extern for strptime
 * Generated by http://jmmk.github.io/javascript-externs-generator
 **********************************************************************/
var strptime = {
  "locale": {
    "A": {},
    "B": {},
    "Bg": {},
    "Date_AdBY": {},
    "Date_dBA": {},
    "Date_dBY": {},
    "Date_dBY_year": {},
    "Date_dBY_year_in_HM": {},
    "Date_dB_in_HM": {},
    "Date_df": {},
    "Date_dfY": {},
    "Date_df_in_HM": {},
    "P": {},
    "X": {},
    "a": {},
    "b": {},
    "bg": {},
    "c": {},
    "day": {},
    "f": {},
    "fg": {},
    "r": {},
    "x": {}
  },
  "parse": function () {},
  "version": {}
};
/**********************************************************************
 * End Generated Extern for strptime
/**********************************************************************/